### ISSUE TITLE
`notebooks.zip` file generated in Makefile does not include `data` subdirectory

### ISSUE THREAD

**Issue by matt-graham** [UCL-RITS/doctoral-programming-intro#43]
The `notebooks.zip` file generated in 

https://github.com/UCL-RITS/doctoral-programming-intro/blob/ab0e1a71d48e436c50167bce82db25a51f5d31d4/Makefile#L27-L28

which is generated to as part of the `site_build.yml` workflow to build the associated web pages (and linked to from there) does not include the `01-beginners/data` subdirectory or the files within it, preventing easily running the associated exemplar notebook without separately downloading the data.

**Comment by ageorgou** [comment]
Semi-related: `make clean` also removes the directory (not sure if intentionally or not).
